server:
  port: 8080
  servlet:
    context-path: /myvote
spring:
  thymeleaf:
    cache: false
    encoding: utf-8
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/myvote?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cssl.entity
  configuration:
    auto-mapping-behavior: full
    use-generated-keys: true
    map-underscore-to-camel-case: true

